title: Default Page

columns:
  - width: 1/2
    fields:
      text:
        label: Text
        type: textarea
        size: large
  - width: 1/2 
    fields:
      noIndex:
        label: turn no-index on for this page?
        type: toggle
        text: yes
      MetaTags:
        label: Meta Tags
        type: textarea
      gallery:
        type: files
        query: page.images
