title: Site
unlisted: false

columns:
  - width: 1/2
    fields:
      ContactFormEmail:
        label: Contact Form To Email
        type: text
      GoogleAnalyticsID:
        label: Google Analytics ID for entire site
        type: text
      FacebookPixelID:
        label: Facebook Pixel ID for entire site
        type: text
  - width: 1/2
    fields:
      pages:
        headline: Pages
        status: published

