title: Site
unlisted: false

fields:
  ContactFormEmail:
    label: Contact Form To Email
    type: text
  GoogleAnalyticsID:
    label: Google Analytics ID for entire site
    type: text
  FacebookPixelID:
    label: Facebook Pixel ID for entire site
    type: text
  pages:
    headline: Pages
    status: published

