title: Site
unlisted: false

fields:
  ContactFormEmail:
    label: Contact Form To Email
    type: text
  GoogleAnalyticsID:
    label: Google Analytics ID for Entire Site
    type: text
  FacebookPixelAPI:
    label: Facebook Pixel API for Entire Site
    type: text
  pages:
    headline: Pages
    status: published

